### PR TITLE
Remove VA domain

### PR DESCRIPTION
**Pull request by kae6114**
VA states the domain vaftl.us was removed from services. CYHYOPS-6178

### CODE REVIEW

**Comment by jsf9k** [comment]
`whois vaftl.us` shows that the domain is still owned by Veterans Affairs.  Are we sure that we want to remove it?

**Review by jsf9k — CHANGES_REQUESTED** [review]
Requesting changes to block this PR until we resolve whether or not we really want to remove the domain.  `whois` indicates that VA still owns the domain.

**Review by jsf9k — APPROVED** [review]
@kae6114 pointed out to me that [this domain is in a "pending delete" state with the registrar](https://who.is/whois/vaftl.us).  That's good enough for me to go ahead and approve.

**Review by mcdonnnj — APPROVED** [review]
Well, if it's good enough for @jsf9k , it's good enough for me. :shipit:

**Review by climber-girl — APPROVED** [review]

**Pull request merged**
