### PR TITLE
Update capitalization to match cisagov/dotgov-data

### PR DESCRIPTION
**Pull request by jsf9k**
## 🗣 Description ##

This pull request:
- Updates a CSV header to agree with [the column names used in cisagov/dotgov-data](https://github.com/cisagov/dotgov-data/blob/main/current-federal.csv).
- Lowercases all domain names to agree with [`current-federal.csv`](https://github.com/cisagov/dotgov-data/blob/main/current-federal.csv).

## 💭 Motivation and context ##

There were [some recent capitalization changes in `current-federal.csv`](https://github.com/cisagov/dotgov-data/commit/e0bd9a9d6b651deacb895cbdf3fecd70f1332cc6), so we should update our derivative file to match.

## 🧪 Testing ##

All automated tests pass.

## ✅ Pre-approval checklist ##

- [x] This PR has an informative and human-readable title.
- [x] Changes are limited to a single goal - *eschew scope creep!*
- [x] All relevant type-of-change labels have been added.
- [x] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
- [x] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
- [x] All new and existing tests pass.

### CODE REVIEW

**Review by dav3r — APPROVED** [review]
👍 👍

**Review by mcdonnnj — APPROVED** [review]
:shipit: As an aside is there anything preventing us from sorting all non-header rows alphabetically? This currently looks like a case-sensitive sorting on the CSV and with everything lowercase it now looks out of sorts.

**Comment by jsf9k** [comment]
> :shipit: As an aside is there anything preventing us from sorting all non-header rows alphabetically? This currently looks like a case-sensitive sorting on the CSV and with everything lowercase it now looks out of sorts.

If you look toward the bottom the domains are not sorted alphabetically.  That's why I didn't bother.

**Comment by jsf9k** [comment]
> :shipit: As an aside is there anything preventing us from sorting all non-header rows alphabetically? This currently looks like a case-sensitive sorting on the CSV and with everything lowercase it now looks out of sorts.

Please see #99.
image

**Pull request merged**
