### PR TITLE
Add 7 non-.gov base domains for HHS

### PR DESCRIPTION
**Pull request by climber-girl**
HHS has requested that these be added in their BOD 18-01 reports.  These have been confirmed as HHS domains by checking the certificates/pages, and HHS has asserted that they are hosted on NIH servers and that NIH is responsible for mitigating any vulnerabilities.

### CODE REVIEW

**Review by mcdonnnj — APPROVED** [review]
Scan all the things 👍

**Review by jsf9k — APPROVED** [review]
:+1:

**Comment by jsf9k** [comment]
@climber-girl, the build GitHub Action should run and return a status when you create a PR from a fork but it is not.  [I am working on fixing that](https://github.com/cisagov/skeleton-generic/pull/29) so that we can merge this PR.

**Review by felddy — APPROVED** [review]
To the MAX!  🐃 ❄️

**Pull request merged**
